import type { HistorialEvento } from '@/entities/historial-evento';

export const MOCK_EVENTOS: HistorialEvento[] = [
  {
    id: '1',
    fecha: '00/00/0000',
    hora: '00:00 a.m.',
    tipo: 'eliminacion',
    titulo: '3 roles removidos',
    detalles: [
      { label: 'Rol removido', valor: 'Empleado' },
      { label: 'Rol removido', valor: 'Empleado' },
      { label: 'Rol removido', valor: 'Empleado' },
    ],
    motivo: '"Ya no aplica como empleado directo, prueba de diseño"',
  },
  {
    id: '2',
    fecha: '00/00/0000',
    hora: '00:00 a.m.',
    tipo: 'eliminacion',
    titulo: '5 roles removidos',
    detalles: [
      { label: 'Rol removido', valor: 'Empleado' },
      { label: 'Rol removido', valor: 'Empleado' },
      { label: 'Rol removido', valor: 'Empleado' },
      { label: 'Rol removido', valor: 'Empleado' },
      { label: 'Rol removido', valor: 'Empleado' },
    ],
    motivo: '"Ya no aplica como empleado directo, prueba de diseño"',
  },
  {
    id: '3',
    fecha: '00/00/0000',
    hora: '00:00 a.m.',
    tipo: 'asignacion',
    titulo: '5 roles asignados',
    detalles: [
      { label: 'Rol asignado', valor: 'Diseñador Junior' },
      { label: 'Rol asignado', valor: 'Diseñador Junior' },
      { label: 'Rol asignado', valor: 'Diseñador Junior' },
      { label: 'Rol asignado', valor: 'Diseñador Junior' },
      { label: 'Rol asignado', valor: 'Diseñador Junior' },
    ],
    motivo: '"Ya no aplica como empleado directo, prueba de diseño"',
  },
  {
    id: '4',
    fecha: '00/00/0000',
    hora: '00:00 a.m.',
    tipo: 'actualizacion',
    titulo: '4 razones sociales actualizadas',
    detalles: [
      { valorAnterior: 'Andina Capital', valor: 'Andina Capital S.A.S - CO...' },
      { valorAnterior: 'Andina Capital', valor: 'Andina Capital S.A.S - CO...' },
      { valorAnterior: 'Andina Capital', valor: 'Andina Capital S.A.S - CO...' },
      { valorAnterior: 'Andina Capital', valor: 'Andina Capital S.A.S - CO...' },
    ],
    motivo: '"Ya no aplica como empleado directo, prueba de diseño"',
  },
  {
    id: '5',
    fecha: '00/00/0000',
    hora: '00:00 a.m.',
    tipo: 'activacion',
    titulo: 'Tercero activado',
  },
  {
    id: '6',
    fecha: '00/00/0000',
    hora: '00:00 a.m.',
    tipo: 'eliminacion',
    titulo: 'Rol removido',
    detalles: [
      { label: 'Rol removido', valor: 'Empleado' },
    ],
    motivo: '"Ya no aplica como empleado directo, prueba de diseño"',
  },
  {
    id: '7',
    fecha: '00/00/0000',
    hora: '00:00 a.m.',
    tipo: 'asignacion',
    titulo: 'Rol asignando',
    detalles: [
      { label: 'Rol asignado', valor: 'Diseñador Junior' },
    ],
  },
  {
    id: '8',
    fecha: '00/00/0000',
    hora: '00:00 a.m.',
    tipo: 'actualizacion',
    titulo: 'Razón social actualizada',
    detalles: [
      { valorAnterior: 'Andina Capital', valor: 'Andina Capital S.A.S - CO...' },
    ],
  },
  {
    id: '9',
    fecha: '00/00/0000',
    hora: '00:00 a.m.',
    tipo: 'activacion',
    titulo: 'Tercero activado',
  },
  {
    id: '10',
    fecha: '00/00/0000',
    hora: '00:00 a.m.',
    tipo: 'asignacion',
    titulo: 'Se designo un contacto como principal',
    detalles: [
      { label: 'Contacto', valor: 'Karol Daniela Madrigal' },
    ],
    motivo: '"Ya no aplica como empleado directo, prueba de diseño"',
  },
  {
    id: '11',
    fecha: '00/00/0000',
    hora: '00:00 a.m.',
    tipo: 'asignacion',
    titulo: 'Se asignó una nueva dirección',
    detalles: [
      { label: 'Dirección', valor: 'Cr 121c #128 b 88\nBogotá - Colombia', chip: 'Correspondencia' },
    ],
  },
  {
    id: '12',
    fecha: '00/00/0000',
    hora: '00:00 a.m.',
    tipo: 'asignacion',
    titulo: 'Se registro un nuevo contacto',
    detalles: [
      { label: 'Contacto', valor: 'Karol Daniela Madrigal Amaya' },
      { label: 'Correo', valor: 'karol.madrigal@sinco.co' },
      { label: 'Contacto', valor: '+57 - 3209982211' },
    ],
  },
];
